language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run prod
before_deploy:
  - cp dist/necktie-doctor-app/index.html dist/tribe-front/404.html
deploy:
  local-dir: dist/necktie-doctor-app
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
