language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run prod
deploy:
  local-dir: www
  provider: firebase
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
  token:
    secure: $FIREBASE_TOKEN
notifications:
  email: false
