language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run prod
before_deploy:
   - cp www/index.html www/404.html
deploy:
  local-dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
notifications:
  email: false
