language: node_js
node_js:
  - "12"
before_script:
  - npm install
script: npm run prod
deploy:
  skip-cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: main
notifications:
  email: false
